JavaWeb - Sw2/src/java/Modelo/PeticionController.java
package Modelo;

import Modelo.util.JsfUtil;
import Modelo.util.PaginationHelper;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "peticionController")
@SessionScoped
public class PeticionController implements Serializable {

    private Peticion current;
    private DataModel items = null;
    @EJB
    private Modelo.PeticionFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PeticionController() {
    }

    public Peticion getSelected() {
        if (current == null) {
            current = new Peticion();
            selectedItemIndex = -1;
        }
        return current;
    }

    private PeticionFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Peticion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Peticion();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PeticionCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Peticion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PeticionUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Peticion) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PeticionDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = Peticion.class)
    public static class PeticionControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PeticionController controller = (PeticionController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "peticionController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Peticion) {
                Peticion o = (Peticion) object;
                return getStringKey(o.getRefPedido());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Peticion.class.getName());
            }
        }

    }

}

JavaWeb - Sw2/web/Controladores/peticion/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatePeticionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePeticionLabel_refPedido}" for="refPedido" />
                    <h:inputText id="refPedido" value="#{peticionController.selected.refPedido}" title="#{bundle.CreatePeticionTitle_refPedido}" required="true" requiredMessage="#{bundle.CreatePeticionRequiredMessage_refPedido}"/>
                    <h:outputLabel value="#{bundle.CreatePeticionLabel_fecha}" for="fecha" />
                    <h:inputText id="fecha" value="#{peticionController.selected.fecha}" title="#{bundle.CreatePeticionTitle_fecha}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreatePeticionLabel_fkIdUsuario}" for="fkIdUsuario" />
                    <h:selectOneMenu id="fkIdUsuario" value="#{peticionController.selected.fkIdUsuario}" title="#{bundle.CreatePeticionTitle_fkIdUsuario}" required="true" requiredMessage="#{bundle.CreatePeticionRequiredMessage_fkIdUsuario}">
                        <f:selectItems value="#{usuarioController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{peticionController.create}" value="#{bundle.CreatePeticionSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{peticionController.prepareList}" value="#{bundle.CreatePeticionShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreatePeticionIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JavaWeb - Sw2/web/Controladores/peticion/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPeticionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPeticionLabel_refPedido}" for="refPedido" />
                    <h:inputText id="refPedido" value="#{peticionController.selected.refPedido}" title="#{bundle.EditPeticionTitle_refPedido}" required="true" requiredMessage="#{bundle.EditPeticionRequiredMessage_refPedido}"/>
                    <h:outputLabel value="#{bundle.EditPeticionLabel_fecha}" for="fecha" />
                    <h:inputText id="fecha" value="#{peticionController.selected.fecha}" title="#{bundle.EditPeticionTitle_fecha}" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditPeticionLabel_fkIdUsuario}" for="fkIdUsuario" />
                    <h:selectOneMenu id="fkIdUsuario" value="#{peticionController.selected.fkIdUsuario}" title="#{bundle.EditPeticionTitle_fkIdUsuario}" required="true" requiredMessage="#{bundle.EditPeticionRequiredMessage_fkIdUsuario}">
                        <f:selectItems value="#{usuarioController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{peticionController.update}" value="#{bundle.EditPeticionSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditPeticionViewLink}"/>
                <br />
                <h:commandLink action="#{peticionController.prepareList}" value="#{bundle.EditPeticionShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditPeticionIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JavaWeb - Sw2/web/Controladores/peticion/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListPeticionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPeticionEmpty}" rendered="#{peticionController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{peticionController.items.rowCount > 0}">
                    <h:outputText value="#{peticionController.pagination.pageFirstItem + 1}..#{peticionController.pagination.pageLastItem + 1}/#{peticionController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{peticionController.previous}" value="#{bundle.Previous} #{peticionController.pagination.pageSize}" rendered="#{peticionController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{peticionController.next}" value="#{bundle.Next} #{peticionController.pagination.pageSize}" rendered="#{peticionController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{peticionController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPeticionTitle_refPedido}"/>
                            </f:facet>
                            <h:outputText value="#{item.refPedido}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPeticionTitle_fecha}"/>
                            </f:facet>
                            <h:outputText value="#{item.fecha}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPeticionTitle_fkIdUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.fkIdUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{peticionController.prepareView}" value="#{bundle.ListPeticionViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{peticionController.prepareEdit}" value="#{bundle.ListPeticionEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{peticionController.destroy}" value="#{bundle.ListPeticionDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{peticionController.prepareCreate}" value="#{bundle.ListPeticionCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListPeticionIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

JavaWeb - Sw2/web/Controladores/peticion/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewPeticionTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewPeticionLabel_refPedido}"/>
                    <h:outputText value="#{peticionController.selected.refPedido}" title="#{bundle.ViewPeticionTitle_refPedido}"/>
                    <h:outputText value="#{bundle.ViewPeticionLabel_fecha}"/>
                    <h:outputText value="#{peticionController.selected.fecha}" title="#{bundle.ViewPeticionTitle_fecha}">
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewPeticionLabel_fkIdUsuario}"/>
                    <h:outputText value="#{peticionController.selected.fkIdUsuario}" title="#{bundle.ViewPeticionTitle_fkIdUsuario}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{peticionController.destroyAndView}" value="#{bundle.ViewPeticionDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewPeticionEditLink}"/>
                <br />
                <h:commandLink action="#{peticionController.prepareCreate}" value="#{bundle.ViewPeticionCreateLink}" />
                <br />
                <h:commandLink action="#{peticionController.prepareList}" value="#{bundle.ViewPeticionShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewPeticionIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>